version: '3.8'

services:

  localidademicroservice:
    image: reirasdev/score-rank:${IMAGE_TAG}
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: net-redis-rankscore